@baseUrl = https://status.is.oregonstate.edu/api/v1

# @name getComponents
GET {{baseUrl}}/components?per_page=100 HTTP/1.1

###

# @name getIncidents
GET {{baseUrl}}/incidents?sort=status&order=desc&per_page=100 HTTP/1.1

