// @baseUrl = https://data.dx.oregonstate.edu
@baseUrl = https://data-dev.dx.oregonstate.edu

# @name getAlerts
GET {{baseUrl}}/jsonapi/node/alerts HTTP/1.1
  ?fields[node--alerts]=title,created,field_alert_content,field_alert_type
  &sort=-field_alert_expiration_date
  &filter[status]=1

###

# @name getAnnouncements
GET {{baseUrl}}/jsonapi/node/announcement HTTP/1.1
  ?fields[node--announcement]=id,title,date,field_announcement_body,field_announcement_action,field_announcement_image,field_audience,field_pages,field_locations,field_affiliation
  &fields[taxonomy_term--pages]=name
  &fields[taxonomy_term--audience]=name
  &fields[taxonomy_term--affiliation]=name
  &fields[taxonomy_term--locations]=name
  &fields[media--image]=name,field_media_image
  &fields[file--file]=filename,filemime,uri
  &include=field_announcement_image,field_announcement_image.field_media_image,field_affiliation,field_audience,field_pages,field_locations
  &filter[status]=1
  &page[limit]=10

###

# @name getCategories
GET {{baseUrl}}/jsonapi/taxonomy_term/categories HTTP/1.1
  ?fields[taxonomy_term--categories]=id,name,field_taxonomy_icon,field_taxonomy_affiliation
  &fields[taxonomy_term--affiliation]=name
  &fields[media--image]=name,field_media_image
  &fields[file--file]=filename,filemime,uri
  &include=field_taxonomy_icon.field_media_image,field_taxonomy_affiliation
  &sort=weight
  &filter[status]=1

###

# @name getCuratedResourcesFeatured
GET {{baseUrl}}/jsonapi/entity_subqueue/featured HTTP/1.1
  ?fields[entity_subqueue--services]=items,drupal_internal__name
  &fields[node--services]=id,title,field_exclude_trending,field_icon_name,field_affiliation,field_audience,field_service_category,field_service_synonyms,field_service_url,field_locations
  &fields[taxonomy_term--categories]=name
  &fields[taxonomy_term--audience]=name
  &fields[taxonomy_term--affiliation]=name
  &fields[taxonomy_term--locations]=name
  &include=items,items.field_affiliation,items.field_audience,items.field_service_category,items.field_locations

###

# @name getContentCard
GET {{baseUrl}}/jsonapi/node/content_card HTTP/1.1
  ?fields[node--content_card]=id,title,body,field_card_footer_link,field_weight,sticky,field_resources,field_machine_name,field_icon_name,field_affiliation,field_audience,field_locations,field_pages
  &fields[taxonomy_term--audience]=name
  &fields[taxonomy_term--affiliation]=name
  &fields[taxonomy_term--locations]=name
  &fields[taxonomy_term--pages]=name
  &fields[node--services]=id
  &include=field_affiliation,field_audience,field_locations,field_pages,field_resources
  &sort=title
  &filter[status]=1

###

# @name getInformation
GET {{baseUrl}}/jsonapi/node/information HTTP/1.1
  ?fields[node--information]=title,field_machine_name,body
  &filter[status]=1

###

# @name getPageContent
GET {{baseUrl}}/jsonapi/node/dashboard_content HTTP/1.1
  ?fields[node--dashboard_content]=title,body
  &filter[field_pages.name]=beta
  &filter[status]=1

###

# @name getReleaseNotes
GET {{baseUrl}}/jsonapi/node/release_notes HTTP/1.1
  ?fields[node--release_notes]=title,body,field_release_notes_date
  &filter[status]=1
  &sort=-created

###

# @name getResources
GET {{baseUrl}}/jsonapi/node/services HTTP/1.1
  ?fields[node--services]=id,title,field_exclude_trending,field_icon_name,field_service_category,field_affiliation,field_audience,field_service_synonyms,field_service_url,field_locations,field_it_systems
  &fields[taxonomy_term--categories]=name
  &fields[taxonomy_term--audience]=name
  &fields[taxonomy_term--affiliation]=name
  &fields[taxonomy_term--locations]=name
  &fields[taxonomy_term--it_systems]=name
  &include=field_affiliation,field_audience,field_service_category,field_locations,field_it_system
  &sort=title
  &filter[status]=1

###

# @name getTrainings
GET {{baseUrl}}/jsonapi/node/trainings HTTP/1.1
  ?fields[node--trainings]=id,title,field_training_audience,field_training_contact,field_training_cost,body,field_training_department,field_training_duration,field_training_featured,field_training_frequency,field_training_prerequisites,field_training_course_design,field_training_image,field_training_tags,field_training_types,field_training_website
  &fields[taxonomy_term--training_audience]=name
  &fields[taxonomy_term--training_course_design]=name
  &fields[taxonomy_term--training_tags]=name
  &fields[taxonomy_term--training_types]=name
  &fields[media--image]=name,field_media_image
  &fields[file--file]=filename,filemime,uri
  &include=field_training_image,field_training_image.field_media_image,field_training_audience,field_training_course_design,field_training_tags,field_training_types
  &filter[status]=1
  &sort=field_training_featured

###

# @name getTrainingAudience
GET {{baseUrl}}/jsonapi/taxonomy_term/training_audience HTTP/1.1
  ?fields[taxonomy_term--training_audience]=id,name
  &filter[status]=1
  &sort=weight

###

# @name getTrainingTags
GET {{baseUrl}}/jsonapi/taxonomy_term/training_tags HTTP/1.1
  ?fields[taxonomy_term--training_tags]=id,name
  &filter[status]=1
  &sort=weight
