@baseUrl = https://api.oregonstate.edu
@client_id = {{$processEnv OSU_API_CLIENT_ID}}
@client_secret = {{$processEnv OSU_API_CLIENT_SECRET}}

# Temporarily set a valid OSU ID to use for testing the API endpoints
# !!! DO NOT COMMIT CHANGES TO THE FOLLOWING LINE !!!
@osuId = 111111111

# @name getToken
POST {{baseUrl}}/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}
&client_secret={{client_secret}}
&grant_type=client_credentials

###
@token = {{getToken.response.body.$.access_token}}

# @name getGpa
GET {{baseUrl}}/v1/students/{{osuId}}/gpa HTTP/1.1
Authorization: Bearer {{token}}

###
@token = {{getToken.response.body.$.access_token}}

# @name getAcademicStatus
GET {{baseUrl}}/v1/students/{{osuId}}/academic-status HTTP/1.1
Authorization: Bearer {{token}}

###
@token = {{getToken.response.body.$.access_token}}

# @name getClassification
GET {{baseUrl}}/v1/students/{{osuId}}/classification HTTP/1.1
Authorization: Bearer {{token}}

###
@token = {{getToken.response.body.$.access_token}}

# @name getPerson
GET {{baseUrl}}/v1/persons/{{osuId}} HTTP/1.1
Authorization: Bearer {{token}}

###
@token = {{getToken.response.body.$.access_token}}

# @name getClassSchedule
GET {{baseUrl}}/v1/students/{{osuId}}/class-schedule HTTP/1.1
Authorization: Bearer {{token}}

###
@token = {{getToken.response.body.$.access_token}}

# @name getMealPlans
GET {{baseUrl}}/v1/persons/{{osuId}}/meal-plans HTTP/1.1
Authorization: Bearer {{token}}

###
@token = {{getToken.response.body.$.access_token}}

# @name getAddresses
GET {{baseUrl}}/v1/persons/{{osuId}}/addresses HTTP/1.1
Authorization: Bearer {{token}}

###
@token = {{getToken.response.body.$.access_token}}

# @name getGrades
GET {{baseUrl}}/v1/students/{{osuId}}/grades HTTP/1.1
Authorization: Bearer {{token}}

###
@token = {{getToken.response.body.$.access_token}}

# @name getHolds
GET {{baseUrl}}/v1/students/{{osuId}}/holds HTTP/1.1
Authorization: Bearer {{token}}

###
@token = {{getToken.response.body.$.access_token}}

# @name getAccountTransactions
GET {{baseUrl}}/v1/students/{{osuId}}/account-transactions?term=current HTTP/1.1
Authorization: Bearer {{token}}

###
@token = {{getToken.response.body.$.access_token}}

# @name getAccountBalance
GET {{baseUrl}}/v1/students/{{osuId}}/account-balance HTTP/1.1
Authorization: Bearer {{token}}
